name: your_job_offer
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  path: any
  uuid: ^4.4.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  go_router: ^14.2.0
  cupertino_icons: ^1.0.2
  flutter_barcode_scanner: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_pin_code_widget: ^0.1.2
  fancy_password_field: ^2.0.7
  intl: ^0.19.0
  file_picker: ^8.1.4
  url_launcher: ^6.3.1
  uni_links:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.7
  json_serializable: ^6.8.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
flutter:
  generate: true
  uses-material-design: true
